// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

#ifndef PROTOBUF_test_2eproto__INCLUDED
#define PROTOBUF_test_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_test_2eproto();
void protobuf_AssignDesc_test_2eproto();
void protobuf_ShutdownFile_test_2eproto();

class student;
class person;

// ===================================================================

class student : public ::google::protobuf::Message {
 public:
  student();
  virtual ~student();

  student(const student& from);

  inline student& operator=(const student& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const student& default_instance();

  void Swap(student* other);

  // implements Message ----------------------------------------------

  student* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const student& from);
  void MergeFrom(const student& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // required int32 age = 2;
  inline bool has_age() const;
  inline void clear_age();
  static const int kAgeFieldNumber = 2;
  inline ::google::protobuf::int32 age() const;
  inline void set_age(::google::protobuf::int32 value);

  // optional string sex = 3;
  inline bool has_sex() const;
  inline void clear_sex();
  static const int kSexFieldNumber = 3;
  inline const ::std::string& sex() const;
  inline void set_sex(const ::std::string& value);
  inline void set_sex(const char* value);
  inline void set_sex(const char* value, size_t size);
  inline ::std::string* mutable_sex();
  inline ::std::string* release_sex();
  inline void set_allocated_sex(::std::string* sex);

  // @@protoc_insertion_point(class_scope:student)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_age();
  inline void clear_has_age();
  inline void set_has_sex();
  inline void clear_has_sex();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  ::std::string* sex_;
  ::google::protobuf::int32 age_;
  friend void  protobuf_AddDesc_test_2eproto();
  friend void protobuf_AssignDesc_test_2eproto();
  friend void protobuf_ShutdownFile_test_2eproto();

  void InitAsDefaultInstance();
  static student* default_instance_;
};
// -------------------------------------------------------------------

class person : public ::google::protobuf::Message {
 public:
  person();
  virtual ~person();

  person(const person& from);

  inline person& operator=(const person& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const person& default_instance();

  void Swap(person* other);

  // implements Message ----------------------------------------------

  person* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const person& from);
  void MergeFrom(const person& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .student member = 1;
  inline int member_size() const;
  inline void clear_member();
  static const int kMemberFieldNumber = 1;
  inline const ::student& member(int index) const;
  inline ::student* mutable_member(int index);
  inline ::student* add_member();
  inline const ::google::protobuf::RepeatedPtrField< ::student >&
      member() const;
  inline ::google::protobuf::RepeatedPtrField< ::student >*
      mutable_member();

  // @@protoc_insertion_point(class_scope:person)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::student > member_;
  friend void  protobuf_AddDesc_test_2eproto();
  friend void protobuf_AssignDesc_test_2eproto();
  friend void protobuf_ShutdownFile_test_2eproto();

  void InitAsDefaultInstance();
  static person* default_instance_;
};
// ===================================================================


// ===================================================================

// student

// required string name = 1;
inline bool student::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void student::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void student::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void student::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& student::name() const {
  // @@protoc_insertion_point(field_get:student.name)
  return *name_;
}
inline void student::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:student.name)
}
inline void student::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:student.name)
}
inline void student::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:student.name)
}
inline ::std::string* student::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:student.name)
  return name_;
}
inline ::std::string* student::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void student::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:student.name)
}

// required int32 age = 2;
inline bool student::has_age() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void student::set_has_age() {
  _has_bits_[0] |= 0x00000002u;
}
inline void student::clear_has_age() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void student::clear_age() {
  age_ = 0;
  clear_has_age();
}
inline ::google::protobuf::int32 student::age() const {
  // @@protoc_insertion_point(field_get:student.age)
  return age_;
}
inline void student::set_age(::google::protobuf::int32 value) {
  set_has_age();
  age_ = value;
  // @@protoc_insertion_point(field_set:student.age)
}

// optional string sex = 3;
inline bool student::has_sex() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void student::set_has_sex() {
  _has_bits_[0] |= 0x00000004u;
}
inline void student::clear_has_sex() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void student::clear_sex() {
  if (sex_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sex_->clear();
  }
  clear_has_sex();
}
inline const ::std::string& student::sex() const {
  // @@protoc_insertion_point(field_get:student.sex)
  return *sex_;
}
inline void student::set_sex(const ::std::string& value) {
  set_has_sex();
  if (sex_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sex_ = new ::std::string;
  }
  sex_->assign(value);
  // @@protoc_insertion_point(field_set:student.sex)
}
inline void student::set_sex(const char* value) {
  set_has_sex();
  if (sex_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sex_ = new ::std::string;
  }
  sex_->assign(value);
  // @@protoc_insertion_point(field_set_char:student.sex)
}
inline void student::set_sex(const char* value, size_t size) {
  set_has_sex();
  if (sex_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sex_ = new ::std::string;
  }
  sex_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:student.sex)
}
inline ::std::string* student::mutable_sex() {
  set_has_sex();
  if (sex_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sex_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:student.sex)
  return sex_;
}
inline ::std::string* student::release_sex() {
  clear_has_sex();
  if (sex_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = sex_;
    sex_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void student::set_allocated_sex(::std::string* sex) {
  if (sex_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete sex_;
  }
  if (sex) {
    set_has_sex();
    sex_ = sex;
  } else {
    clear_has_sex();
    sex_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:student.sex)
}

// -------------------------------------------------------------------

// person

// repeated .student member = 1;
inline int person::member_size() const {
  return member_.size();
}
inline void person::clear_member() {
  member_.Clear();
}
inline const ::student& person::member(int index) const {
  // @@protoc_insertion_point(field_get:person.member)
  return member_.Get(index);
}
inline ::student* person::mutable_member(int index) {
  // @@protoc_insertion_point(field_mutable:person.member)
  return member_.Mutable(index);
}
inline ::student* person::add_member() {
  // @@protoc_insertion_point(field_add:person.member)
  return member_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::student >&
person::member() const {
  // @@protoc_insertion_point(field_list:person.member)
  return member_;
}
inline ::google::protobuf::RepeatedPtrField< ::student >*
person::mutable_member() {
  // @@protoc_insertion_point(field_mutable_list:person.member)
  return &member_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_test_2eproto__INCLUDED
